# Generated by Django 5.1 on 2024-08-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_ID', models.EmailField(max_length=254)),
                ('Question', models.TextField()),
            ],
        ),
    ]
