# Generated by Django 5.1 on 2024-08-11 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiryApp', '0003_trauma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trauma',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Email', to='enquiryApp.enquiry'),
        ),
    ]
