# Generated by Django 5.1 on 2024-08-11 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiryApp', '0004_alter_trauma_tid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SID', to='enquiryApp.sound')),
            ],
        ),
    ]
