# Generated by Django 5.1 on 2024-08-11 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiryApp', '0005_sound_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='VVV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.IntegerField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enquiryApp.sound')),
            ],
        ),
    ]
