# Generated by Django 5.1 on 2024-08-12 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiryApp', '0006_vvv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Pname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('Cid', models.IntegerField(primary_key=True, serialize=False)),
                ('CName', models.CharField(max_length=10)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiryApp.parent')),
            ],
        ),
    ]
