# Generated by Django 5.1 on 2024-08-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiryApp', '0007_parent_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='music',
            name='mid',
        ),
        migrations.RemoveField(
            model_name='vvv',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Stroke',
        ),
        migrations.RemoveField(
            model_name='trauma',
            name='tid',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.DeleteModel(
            name='Sound',
        ),
        migrations.DeleteModel(
            name='VVV',
        ),
        migrations.DeleteModel(
            name='Trauma',
        ),
    ]
