# Generated by Django 5.1 on 2024-08-12 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('Bid', models.IntegerField(primary_key=True, serialize=False)),
                ('Bname', models.CharField(max_length=30)),
                ('Bhod', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Cid', models.IntegerField(primary_key=True, serialize=False)),
                ('Cname', models.CharField(max_length=30)),
                ('Cdetail', models.TextField()),
                ('Bid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectionApp.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('Fid', models.IntegerField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=30)),
                ('Fdate', models.DateField()),
                ('Bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectionApp.branch')),
                ('Cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collectionApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Sid', models.IntegerField(primary_key=True, serialize=False)),
                ('Sname', models.CharField(max_length=30)),
                ('Sdob', models.DateField()),
                ('Syear', models.SmallIntegerField()),
                ('Bid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectionApp.branch')),
            ],
        ),
    ]
