# Generated by Django 5.1 on 2024-08-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('Cid', 'Bid'), name='unique_Cid_Bid'),
        ),
    ]
