# Generated by Django 5.1 on 2024-08-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectionApp', '0002_course_unique_cid_bid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'managed': False},
        ),
    ]
