# Generated by Django 5.1 on 2024-08-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectionApp', '0003_alter_course_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
    ]
